# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: TJHeuvel.net - Blog
email: info@tjheuvel.net
description: > # this means to ignore newlines until "baseurl:"
  Freelance dev who wants to write things down
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://blog.tjheuvel.net" # the base hostname & protocol for your site
twitter_username: tjheuvel
github_username:  tjheuvel

# Build settings
markdown: kramdown

# Custom

permalink: "/:title"